package co.fredyjimenezrendon.proyectobase.dto;
// Generated 10-dic-2016 18:27:30 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "prueba_bd")
public class Usuario implements Serializable {

	private static final long serialVersionUID = -3154017653132039598L;
	
	private Integer idUsuario;
	private String login;
	private String password;
	private Date fechaInicial;
	private boolean habilitado;

	public Usuario() {
		//Contructor vacio para hibernate
	}

	public Usuario(String login, String password, Date fechaInicial, boolean habilitado) {
		this.login = login;
		this.password = password;
		this.fechaInicial = fechaInicial;
		this.habilitado = habilitado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_usuario", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "login", nullable = false, length = 50)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicial", nullable = false, length = 19)
	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

}
